from gra.game import Location

locations = [
    Location(0, "Start gry", " ", None, "Witaj! Możesz przejść do lokacji 1 lub 2", [1, 2]),
    Location(1, "Obóz wojowników", "iść do obozu wojowników", None, "Jesteś w Obozie wojowników. Wokół siebie widzisz ludzi uzbrojonych po zęby rozmawiających na różne tematy. Możesz tutaj spokojnie odpocząć przed następną wyprawą w nieznane.", 1),
    Location(2, "Miasto kupne", "iść do miasta kupnego", None, "Jesteś w mieście. Otaczają Cię ulice tętniące życiem, wydaje się niemal idealne. Kupce targują się, rodziny spacerują i życie się toczy. Jednak wiesz że coś jest nie tak, ciemne uliczki skrywające sekrety, plotki pełne kłamstw. Wpada Ci w ucho plotka o tak zwanym bazyliszku. Nigdy o czymś takim nie słyszałeś.", 1),
    Location(3, "Dom rzeźbiarza", "iść do domu rzeźbiarza", None, "Wychodzisz do pustego domu rzeźbiarza...", 1),
    Location(4, "Arena", "iść na arenę", None, "Jesteś na arenie. Tutaj każdy może się zapisać i walczyć o śmierć i życie za chwałę i pieniądze. Widzowie krzyczą z podekscytowania z każdym ciosem, wiedząc że jeden z nich będzie śmiertelny. ", 1),
    Location(5, "Karczma 7.5 drwali", "iść do karczmy drwali", None, "Wchodzisz do pobliskiej karczmy. Jest tu dość pusto, jedynie trio wieśniaków pijących w kącie oraz rolnik zapijający smutki przy ladie. W samym tyle znajdują się drzwi które wydają się jakby nie pasowały tutaj. ", 1),
    Location(6, "Farma jakiegoś fajnego gościa", "iść na farmę", None, "--", 1),
    Location(7, "Las tysiącletni", "iść do lasu", None, "Jesteś w tysiącletnim lesie. Wokół Ciebie są tylko gigantyczne drzewa, większe od niektórych wierzy. Słyszysz dalekie odgłosy życia w lesie, znasz to miejsce, jednak łatwo się tutaj zgubić. Trzymaj się drogi jeśli Ci życie miłe.", 1),
    Location(8, "Ruiny starej wieży", "iść do ruin starej wieży", None, "Opis: W głebi lasu znajdujesz starą wieże. Słyszałeś o niej w legendach i plotkach od ludzi z obozu. Mówi się że spaliła ją chimera, ale to było setki lat temu. Wieża nie jest wysoka, górne poziomy są zawalone, jednak kilka poziomów nadal można zwiedzić. Uważaj na szkielety dawnych rycerzy.", 1),
    Location(9, "Studnia bez końca", "iść do studni", None, "Opis : Przed tobą widzisz dużą studnie. Widać że od dawna nie była używana. Patrząc na nią bliżej, zauważasz wajchę. Ciągnąc za nią, pokazują się schody prowadzące w głębię studni. Mówi się że prowadzi do środka ziemi, ludzie którzy wędrowali w głebi wracają z poparzeniami gorszymi niż od smoka. Przygotuj się.", 1),
    Location(10, "Labirynt ", "iść do labiryntu", None, "Jesteś w labiryncie. Sciany wokół Ciebie wydają się masywne, niezniszczalne. Na każdym rogu widzisz szczątki poprzednich nieszczęśników którzy tutaj trafili. Ciarki Cię przechodzą gdy przypominasz sobie co grasuje w tym labiryncie. Mówi się że minotaur jest niepokonany, gdy Cię zobaczy, jesteś martwy. Znajdź wyjście i przygotuj się na cokolwiek możesz tutaj napotkać.", 1),
    Location(11, "Bagna ", "iść na bagna", None, "Opis : Jesteś na bagnach. Gęsta mgła sprawia że trudno cokolwiek zobaczyć, a błoto spowalnia każdy Twój ruch. Bagna to niebezpieczne miejsce, uważaj na czające się w wodzie gady. Gdzieś w głebi tych terenów mieszka wiedźma. ", 1),
    Location(12, "Smocze góry", "iść do lasu", None, "Opis : Droga w góry jest długa i trudna, ciężki wiatr ze śniegiem ograniczają Twoją wizję. W tych górach żyją potężne stwory czychające w jaskiniach. Najbezpieczniejszą opcją jest trzymanie się ścieżki. Mówi się że na samym szczycie znajduje się gniazdo smoków. Nawet jedno jajo można sprzedać za fortunę a smocze szczątki można przerobić na potężne przedmioty.", 1),
    Location(13, "Ruiny zamku Karad", "iść do lasu", None, "Opis : Przed tobą znajdują się ruiny zamku Karad. ", 1),
    Location(14, "Karczma \"Mały Łowca", "iść do lasu", None, "Jesteś w tysiącletnim lesie. Wokół Ciebie są tylko gigantyczne drzewa, większe od niektórych wierzy. Słyszysz dalekie odgłosy życia w lesie, znasz to miejsce, jednak łatwo się tutaj zgubić. Trzymaj się drogi jeśli Ci życie miłe.", 1)
]
